### PR TITLE
Add Fluence transport

### PR DESCRIPTION
**Pull request by folex**
We've implemented a transport for metadata on top of decentralized Redis running on Fluence. The following methods are implemented:
- `fetch`
- `list`
- `add`
- `newlisturls`
- `newdatabase`
- `newtable`
- `get`
- `set`
- `getall`
- `keys`

Since we're using Redis here and it is also possible to use SQLite (or both at once), I think more methods could be implemented, but I'm not sure if that would be useful. If so, it would be awesome to discuss their implementation.

As transport is implemented, it would be great to integrate it with Internet Archive, and I hope for your help with that!

Would love to answer or discuss any questions. Thanks in advance :)

### CODE REVIEW

**Comment by mitra42** [comment]
Hi - this all looks good to me, except for some changes I'm making for the 2.0.0 version of dweb-transports which is about to go live, just dependent on a fix from WOLK. 

The problem was that the bundle was getting overweight, by the time it had Gun, Webtorrent, IPFS, Wolk in it. So I'm splitting it out, and for browsers I'm including the transports own bundle with a <Script> tag, for example I can get IPFS from "https://cdn.jsdelivr.net/npm/ipfs/dist/index.min.js" (its just a file in their NPM distro) Do you have such a bundle ? Typically those bundles set the same global you are currently setting with `const influence = require('influence')` 

If you can give me the file name / URL then I'll just drop it into the code in the right place when I merge it, and make the similar changes required for nodejs. 

If this isn't clear then I'm happy to jump on a call.

**Comment by folex** [comment]
Hi! We've uploaded minified bundle https://cdn.jsdelivr.net/npm/fluence@0.3.14/bundle/bundle.js

It's kinda big right now – 4.7MB, we'll work on that.

Please let me know if that works OK. Will be glad to take testing and debugging the integration on our part, so let me know if there would be any problems.

P.S. ~in~fluence* :)

**Comment by folex** [comment]
@mitra42 
We've made a ~100KB bundle, removed some deps that were unnecessary for internet archive

https://cdn.jsdelivr.net/npm/fluence@0.3.14-no-webj/bundle/bundle.js

**Comment by mitra42** [comment]
Great - an hour or so ago I pushed a new version of dweb-transports and its bundle that incorporates Fluence. Its turned off by default till its tested, but its usable now. 

Next step is figuring out how to map the archive URLs to fluence urls and put that in, that might require a call if its not obvious, you can see examples of mapping to Gun and Wolk in dweb-transports/Naming.js

I'll put this lighter bundle in the next release (which I'd anticipate will be as soon as we've tested the current one).

**Comment by mitra42** [comment]
That lighter bundle was pushed to github and published on NPM last night.

**Pull request merged**
